### ISSUE TITLE
Implement time tracking

### ISSUE THREAD

**Issue by jacobj10** [vector-track/asset-tracker#1]
- [ ] Add simple start stop feature, should support multiple things started/stopped.
- [ ] Recursively update tracking up to root.
- [ ] Add basic dashboard for the above
